language: R
cache: packages
warnings_are_errors: true
sudo: required

matrix:
  include:
    - os: linux
      r: release
    
    - os: linux
      r: devel
      
    - os: osx
      r: release

    - os: osx
      r: devel

r_packages:
- Rcpp
- RcppArmadillo
- fastcluster
- reshape2
- pheatmap
- ellipse
- truncnorm
- tibble
- lazyeval
- foreach
- doParallel
- itertools
- microbenchmark
- viridis
- covr

r_github_packages:
- hadley/scales
- hadley/ggplot2

after_success:
  - Rscript -e 'covr::codecov(type ="all")'

r_check_args: "--as-cran --timings"
